#!/bin/bash
#Create Network

# allow access from localhost
xhost + 127.0.0.1

# run with X11 forwarding and keep running until it quits
docker run -it --rm --network host --privileged -e DISPLAY=docker.for.mac.localhost:0 -v /tmp/.X11-unix:/tmp/.X11-unix -v /lib/modules:/lib/modules mininet
